#!/bin/sh

# editors
export SVN_EDITOR=nano
export EDITOR=nano

# locale
export LANG=en_US.UTF-8
export LC_CTYPE="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_ALL=

# colored ls
if [ "$TERM" != "dumb" ]; then
    if hash dircolors 2>/dev/null; then
        export LS_OPTIONS='--color=auto'
        eval "$(dircolors "$XDG_CONFIG_HOME/dircolors/dircolors")"
    fi
fi

# ssh-pageant
if hash ssh-pageant 2>/dev/null; then
    eval "$(ssh-pageant -qra ~/.ssh/pageant)"
fi

# MacPorts Maven Home
if [ -d /opt/local/share/java/maven3 ]; then
    export M2_HOME="/opt/local/share/java/maven3"
fi

export HOMEBREW_NO_ANALYTICS=1

# macOS JAVA_HOME
if [ -f "/usr/libexec/java_home" ]; then
    JAVA_HOME=$(/usr/libexec/java_home)
    export JAVA_HOME
fi

# GRAALVM_HOME
if [ -d /Library/Java/JavaVirtualMachines/openjdk17-graalvm ]; then
    export GRAALVM_HOME="/Library/Java/JavaVirtualMachines/openjdk17-graalvm/Contents/Home"
fi

if hash dotnet 2>/dev/null; then
    export DOTNET_CLI_TELEMETRY_OPTOUT='1'
fi

if [ -f "${HOME}/.kube/config" ]; then
    export KUBECONFIG="${HOME}/.kube/config"
fi

if [ -f "${HOME}/.kube/setup-kubeconfig-env.sh" ]; then
    . "${HOME}/.kube/setup-kubeconfig-env.sh"
fi

# sdkman
if [ -d "${HOME}/.sdkman" ]; then
    export SDKMAN_DIR="${HOME}/.sdkman"
    [ -s "$HOME/.sdkman/bin/sdkman-init.sh" ] && . "$HOME/.sdkman/bin/sdkman-init.sh"
fi

export GOPATH="${HOME}/Developer/go"
