#!/bin/sh

# Homebrew
if [ -n "${PATH##*/usr/local/bin*}" ]; then
    export PATH="/usr/local/bin:${PATH}"
fi

# MacPorts
if [ -d /opt/local ]; then
    export PATH="/opt/local/bin:/opt/local/sbin:${PATH}"

    # MacPorts Apache binaries
    if [ -d /opt/local/apache2/bin ]; then
        export PATH="/opt/local/apache2/bin:${PATH}"
    fi

    # MacPorts PostgreSQL binaries
    if [ -d /opt/local/lib/postgresql92/bin ]; then
        export PATH="/opt/local/lib/postgresql92/bin:${PATH}"
    fi
fi

# rbenv
if [ -d "${HOME}/.rbenv/bin" ]; then
    export PATH="${HOME}/.rbenv/bin:${PATH}"
fi

if hash rbenv 2>/dev/null; then
    eval "$(rbenv init - "$(basename "${SHELL}")")"
fi

if [ -d "${HOME}/bin" ]; then
    export PATH="${PATH}:${HOME}/bin"
fi

# nix
if [ -d /nix ]; then
    . ~/.nix-profile/etc/profile.d/nix.sh
fi

# Android
if [ -d "${HOME}/Library/Android/sdk" ]; then
    export ANDROID_HOME="${HOME}/Library/Android/sdk"
    export PATH="${PATH}:$ANDROID_HOME/tools"
    export PATH="${PATH}:$ANDROID_HOME/platform-tools"
fi

if [ -d "/usr/local/share/android-sdk" ]; then
    export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
fi

# go
if hash go 2>/dev/null; then
    PATH="${PATH}:$(go env GOPATH)/bin"
    export PATH
fi

if [ -d "${HOME}/.dotnet/tools" ]; then
    export PATH="${PATH}:${HOME}/.dotnet/tools"
fi

if ! hash mysql 2>/dev/null && [ -d "/usr/local/opt/mysql-client/bin" ]; then
    export PATH="/usr/local/opt/mysql-client/bin:$PATH"
fi

if [ -d "${HOME}/Library/Python/3.9/bin" ]; then
    export PATH="${PATH}:${HOME}/Library/Python/3.9/bin"
fi

# phpenv
if [ -d "${HOME}/.phpenv" ]; then
    export PHPENV_ROOT="${HOME}/.phpenv"
    export PATH="${PHPENV_ROOT}/bin:${PATH}"
    eval "$(phpenv init -)"
fi
