@echo off

setlocal EnableDelayedExpansion

set registryRoot=HKCU\Software\Classes

reg delete %registryRoot%\*\shell\grepWin...
reg delete %registryRoot%\*\shell\grepWin...
reg delete %registryRoot%\Directory\background\shell\grepWin...
reg delete %registryRoot%\Directory\shell\grepWin...
reg delete %registryRoot%\Drive\shell\grepWin...
reg delete %registryRoot%\Folder\shell\grepWin...
