#!/bin/sh

# MacPorts bash-completion
if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
    . /opt/local/etc/profile.d/bash_completion.sh
fi

# Homebrew bash-completion
if hash brew 2>/dev/null; then
    brewPrefix=$(brew --prefix)
    if [ -f "${brewPrefix}/etc/bash_completion" ]; then
        . "${brewPrefix}/etc/bash_completion"
    fi
fi

if [ -f ~/.rbenv/completions/rbenv.bash ]; then
    . ~/.rbenv/completions/rbenv.bash
fi

if hash bazel 2>/dev/null; then
    . "$XDG_CONFIG_HOME/bash/completions.d/bazel-complete.bash"
fi

. "$XDG_CONFIG_HOME/shell/completions"
