#!/bin/sh

. "$XDG_CONFIG_HOME/shell/paths"
. "$XDG_CONFIG_HOME/shell/config"

# Google Cloud SDK
if [ -d /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk ]; then
    . "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
    . "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
fi
