[tools]
aws = { version = "2.36.39", symlink_bins = "true" }
azure = { version = "2.90.0", dependency_prereleases = "allow", with = ["pip"] }
"github:Arlol/chorito" = "2609.0.132"
"github:arlol/drifty" = "2609.0.146"
go = "1.26.6"
java = "temurin-26.0.0"
node = "24.19.0"
pkl = "0.32.1"
python = "3.14.7"
ruby = "4.0.6"
rust = "1.98.0"

[settings]
idiomatic_version_file_enable_tools = ["java", "ruby", "node", "python"]

[settings.ruby]
compile = true
